### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jimpaw** [nutti/Copy-And-Paste-UV#21]
I find this script very useful but some things really slows me down. One of the biggest issues is that the script very often flips the copied uv in the wrong way. Its a little frustrating having to first go throught menus when you click(u) and then open up the left tab and find the rotate/flip buttons. 

Maybe you should make a pie menu of this script instead? that would make it super fast. 

another function that would be nice is to be able to select one face as "copy" and then select many faces and paste that face in all of the selected faces instead of having to do it one at the time. If you 

want to i could sketch up a pie menu for you  with some more suggestions of function and layout?

Kindly // Jimmy

**Comment by nutti** [comment]
Thank you for your great feature/UI request!

> Maybe you should make a pie menu of this script instead? that would make it super fast. 

I see. It looks cool!
I did not come up with your suggestion.
I made new issue about this. #22

>another function that would be nice is to be able to select one face as "copy" and then select many faces and paste that face in all of the selected faces instead of having to do it one at the time.

OK.
I made new issue about this too. #23

> If you want to i could sketch up a pie menu for you with some more suggestions of function and layout?

Yes, please!
If you have no problem, please post on #22 .

**Comment by nutti** [comment]
@Jimpaw 

Hi!
I made prototype about #23 .

you can download prototype version below links.
https://github.com/nutti/Copy-And-Paste-UV/archive/spike_v4.0.zip

Please try this feature.
Instruction is here.

1. Copy UV
2. Paste UV - Plural

**Comment by mifth** [comment]
Don't you think that every artist should make his own pie menues?
What if the pie menu will override my own other pie menu?

I would leave it for artisits.

**Comment by nutti** [comment]
@Jinpaw

Is Pie menu feature related to #19 ?
A link to image is no longer available.

**Comment by nutti** [comment]
@mifth 

I think you are right.

But @Jimpaw seems to say that options on tool-shelf should be added to Pie menu.
Because I'm not expert about Pie menu, please tell me.
If add-on user does operation, is it possible to show Pie menu which options on tool-shelf are registered?
If it is possible, I think this UI has a value to discuss.

If @Jimpaw want to add default(?) Pie menu, it becomes a problem.
However, we propose a method to switch enable/disable, there is room for consideration.

**Comment by mifth** [comment]
Hi.
actually, i don‘t know any addon which has pie menu. pie menues are for customization. this is a custom for every different user.

example of custom pie menues http://blenderartists.org/forum/showthread.php?348496-Addon-Wazou-s-Pie-Menus

the guy did custom pies for his tools and his addons.
that‘s a personal thing.

problem 1:
I we bind a pie menu to alt-c key for example - another user can use this key fot his another tools.

I think pie menu is really personal thing. this is not addon job.

**Comment by mifth** [comment]
About option registration - it‘s possible to use AddonPreferences to set some checkboxes to the addon.
you can check my scripts:
Simple3dcoat
supergrouper

they have addon preferences.

**Comment by Jimpaw** [comment]
Mifth 

I completely see your point. From my point of view everything you do should be made so that the end user can customize things the way they would like to use it so i completely agree with you there.  My suggestion is simply to give users a choice to use a pie, and choose a shortcut in the settings. Do you guys have a better sollution for taking away the fact that you have to scroll down in the left panel and press buttons everytime you use copy and paste and it doesnt work? (flip,rotate uv:s etc) or any suggestion on how to make the commands copy and paste more upfront instead of beeing in a sub menu? 

From my point of view pies menus are made to make your workflow faster (that because they welcome customization) But if you have any faster way i think you should go for that. 

Anyway thanks for an awsome script! any updates on when the copy and paste functions will work better? 

Kindly // Jimmy

**Comment by mifth** [comment]
@Jimpaw hi.

About pie menu:
No add-ons make their own pie menus. It's difficult to maintain them.
And this is really a custom thing for every user.
Here is example where a guy did a pie for Mira toolshttp://blenderartists.org/forum/showthread.php?366107-MiraTools&p=2875798&viewfull=1#post2875798
But this is a really personal thing for an artist. And this will not be in Mira tools.
You should make your own pie menu. It's easy.
About together menus for the left panel we need to as @Nutty.

**Comment by mifth** [comment]
About other menues for the left panel we need to ask @Nutty *

**Comment by Jimpaw** [comment]
Actually pie menus are not that hard to maintain (at least for a script in this caliber) but i see your point. i will follow your guys, its gonna be fun to see how this evolves, best of luck!

**Comment by nutti** [comment]
@Jinpaw

Hi,

IMO, Pie menu should be maintained by user.
However, there is a room for discussion about **left menu**.

Is it possible to register left menu to Pie menu?
And what behavior when register left menu to Pie menu?

**Comment by nutti** [comment]
@mifth @Jimpaw 

Now, I would like to close this issue.
Pie menu is beyond the scope of this add-on.

**Comment by mifth** [comment]
Yep, close it.

**Comment by nutti** [comment]
Thanks.

I closed it.
