### ISSUE TITLE
New feature: N to M copy/paste UV

### ISSUE THREAD

**Issue by nutti** [nutti/Copy-And-Paste-UV#23]
This issue is mentioned #21 .

This add-on does not support N to M copy/paste UV.
So, copying UV is frustrating when user pastes more than 2 polygons.

**Comment by nutti** [comment]
I made prototype.

you can download prototype version below links.
https://github.com/nutti/Copy-And-Paste-UV/archive/spike_v4.0.zip

Please try this feature.
Instruction is here.

1. Copy UV
2. Paste UV - Plural

**Comment by Jimpaw** [comment]
Sure i will try it out!

**Comment by Jimpaw** [comment]
It worked but with various result. i left an image on blender artist tread.

**Comment by nutti** [comment]
If you copy/paste UV by default operation, does same problem occur?

* Select face
* Copy UV
* Select problematic face
* Paste UV

If so, you must flip/rotate UV about problematic face.
This feature is only extention about default Copy/Paste UV.

**Comment by nutti** [comment]
@Jimpaw 

Hi,

I will rewrite feature **Copy/Paste UV** to achieve copy/paste UVs more smart way.
I think I can solve your problem if targeted polygon is adjacent.

**Comment by Jimpaw** [comment]
Okay thanks for that! Any progress?

**Comment by nutti** [comment]
@Jinpaw

Sorry I have no progress now.

And I have a suggestion about tis feature.
Your problem may be solved when faces are adjacent.
However, if faces are not adjacet, it may occur same problem.

Is this limitation within an allowance?

**Comment by nutti** [comment]
@Jimpaw 

Hi,

I think your problem mentioned at below links is somewhat definite situation.
http://blenderartists.org/forum/showthread.php?348421-Addon-Copy-and-Paste-UV-Coordinates&p=2889606&viewfull=1#post2889606

Most of models are not plate mesh and do not use only rectangle polygon.
However, this problem focuses on plate mesh.
Then, I would not fix for the sake of solving this particular situation.
(e.g. There is no correct answer when this problem extends to sphere mesh)

I think current implementation and flip/rotate operation meet the requirement of this problem.
What do you think?

**Comment by nutti** [comment]
@Jimpaw 

In addition,
If someone use this feature to the mesh you mentioned as problem, someone think this is correct result because there is difference among these meshes.

**Comment by nutti** [comment]
Supported N:M copy/paste.
You can select strategy from property on tool-shelf.

https://github.com/nutti/Copy-And-Paste-UV/tree/spike_v4.0
