### ISSUE TITLE
Partially copy/paste UV 

### ISSUE THREAD

**Issue by nutti** [nutti/Copy-And-Paste-UV#29]
Partially copy/paste UV island feature requested by @Jakasan.

**Comment by mifth** [comment]
i thik I can try to add it to Transfer UV. We can use hide/unhide state of faces.

**Comment by nutti** [comment]
Are you going to add this feature as new operation?
If so, you can add new file.

**Comment by mifth** [comment]
It can be in the same operators.
I think it's just 3-5 lines to change for the transfer algorithm.

**Comment by nutti** [comment]
@mifth 

Oh, great!!
this feature should be in v3.2 same as #11 .

**Comment by nutti** [comment]
@mifth 

Please implement this feature after pull req #28 is over and merged into develop branch.

**Comment by nutti** [comment]
I merged your pull req.
Then, you can implement this issue.

**Comment by mifth** [comment]
@nutti Ok i checked it. And this is really one line of code.

Here is the new pull request: https://github.com/nutti/Copy-And-Paste-UV/pull/30
Here is my test: http://youtu.be/WPtzYej6n0Y

It will be possible to copy/paste for parts of mesh.

**Comment by nutti** [comment]
@mifth 

It's amazing!!!
There is no question about this pull request.
Then, I merged your pull request.

Thanks!!

**Comment by mifth** [comment]
:)

**Comment by Jakasan** [comment]
Super, go to test :)
