### ISSUE TITLE
Rename add-on's name

### ISSUE THREAD

**Issue by nutti** [nutti/Copy-And-Paste-UV#32]
This add-on has some requests unrelated to copy/past UV.
These requests are very powerful feature for UV tool.
So, we think this add-on should include these features and rename.

We think that new add-on name should be **UV tools**.
If there are any better names, please tell us.

**Comment by mifth** [comment]
Uv toolz? :)

**Comment by nutti** [comment]
@mifth

Is there any diffence between toolz and tools?

**Comment by mifth** [comment]
No difference. it just sounds good.

**Comment by nutti** [comment]
@mifth 

Sounds good :-)
I think UV tools is something common.
UV toolz is better.

**Comment by mifth** [comment]
Great too. :)
It will be more in style. Like hip-hop uses zzzz a lot.

**Comment by nutti** [comment]
@mifth 

Hi, sorry for stopping development for several months.
I just resume development now.

I think, **UV toolz** is similar to add-on name below link.
http://blenderartists.org/forum/showthread.php?294904-AddOn-UV_Tool

So, we should rename.
I think **Magic UV** is good candidate for this add-on mentioned #31 .

What do you think?

**Comment by mifth** [comment]
Hi.

Welcome back. It's good name. I like it. )

**Comment by nutti** [comment]
I renamed this add-on "Copy and Paste UV" to "Magic UV".

https://github.com/nutti/Copy-And-Paste-UV/tree/spike_v4.0

So, I close this task.
