### ISSUE TITLE
New feature: Transform texture island by bounding box

### ISSUE THREAD

**Issue by nutti** [nutti/Copy-And-Paste-UV#34]
@eXKR requests this feature in [Blender Artist](http://blenderartists.org/forum/showthread.php?348421-Addon-Copy-and-Paste-UV-Coordinates&p=2877225&viewfull=1#post2877225)

Transform UV island using **Bounding Box Selection** likes Photoshop/GIMP/etc...

**Comment by mifth** [comment]
This feature is already in blender. Just select all faces and press "reset" in u menu.
I would not spare my time for the feature which is already in blender. :)

**Comment by nutti** [comment]
@mifth 

Ah..., sorry you may mislead about this feature because of my bad explanation.
This feature is for **UV/Image Editor** not for 3D View.
If faces are selected, their UVs are displayed in UV/Image Editor.
This feature can transform their UVs by bounding box like as photoshop selection.

Here is a example video.
You can see bounding box around UV in right down windows, and transform UV using bounding box.
https://youtu.be/QH3G9qZgjfw?t=4m8s

**Comment by nutti** [comment]
Some improvement is needed about this feature.
However, this is my homework until v4.0 release.
